version: "3"
services:
  nginx:
    image: whattheearl/nginx-proxy:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - MOCHIBEAN_HOSTNAME=mochibean.com
      - MOCHIBEAN_TARGET=http://wordpress:80
      - JEARL_HOSTNAME=jearl.io
      - JEARL_TARGET=http://jearl.io:80
    volumes:
      - /nginx-proxy/ssl:/ssl