version: "3"
services:
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - MOCHIBEAN_HOSTNAME=mochibean.com
      - MOCHIBEAN_TARGET=http://wordpress:80
      - JEARL_HOSTNAME=jearl.io
      - JEARL_TARGET=http://jearl.io:80
    volumes:
      - ./ssl/:/ssl/
networks:
  default:
    external: true
    name: mochibeancom_default