version: "3"
services:
  nginx:
    build: .
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-proxy/sites-enabled/:/nginx-proxy/sites-enabled/
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
networks:
  default:
    name: ingress